plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
    id 'application'
}

group = 'br.com.syrxmc.bot'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:deprecation'
}

repositories {
    mavenCentral()
}

application {
    mainClass = "br.com.syrxmc.bot.Main"
}

dependencies {

    implementation 'net.dv8tion:JDA:6.4.2'

    implementation 'org.quartz-scheduler:quartz:2.5.2'
    implementation 'ch.qos.logback:logback-classic:1.5.34'
    implementation 'org.reflections:reflections:0.10.2'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.0'

    compileOnly "org.projectlombok:lombok:1.18.46"
    annotationProcessor "org.projectlombok:lombok:1.18.46"
}

shadowJar {
    archiveBaseName.set('SyrxBot')
    archiveClassifier.set('')
    archiveVersion.set('')
}
